# Generated by Django 4.2.5 on 2023-09-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectmarks',
            unique_together={('student',), ('subject',)},
        ),
    ]
