# Generated by Django 4.2.5 on 2023-09-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card')},
        ),
    ]
